services:
  app:
    image: mcr.microsoft.com/devcontainers/php:1-8.3-bullseye
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}
    working_dir: /workspaces/${localWorkspaceFolderBasename}
    command: /bin/bash -lc "sleep infinity"
    depends_on:
      - db
      - redis
      - mailpit
      - meilisearch
      - minio
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: laravel
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  mailpit:
    image: axllent/mailpit:latest
    ports: ["8025:8025","1025:1025"]
  meilisearch:
    image: getmeili/meilisearch:latest
    environment: { MEILI_NO_ANALYTICS: 'true' }
    ports: ["7700:7700"]
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
