name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear steps to reproduce
    validations:
      required: true
