name: CI
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring
          coverage: none
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpstan || true
      - run: vendor/bin/deptrac analyze || true
      - run: php -v
